INSERT INTO CLIENT (COGNOMS,DATA_ALTA,NOM) VALUES ('Picapiedra','2000-11-11','Pedro');
INSERT INTO CLIENT (COGNOMS,DATA_ALTA,NOM) VALUES ('Ketchum','2000-11-11','Ash');
INSERT INTO CLIENT (COGNOMS,DATA_ALTA,NOM) VALUES ('Colega','2000-11-11','Turbo');